### ISSUE TITLE
building Pytorch freeze

### ISSUE THREAD

**Issue by loupdmer** [meeki007/Jetpack-installs#1]
Hi, I am trying to build pytorch1.10 and torchvision for python3.9 following your HowTo.
I am stuck when it comes to build it :during the following command  `python3 setup.py bdist_wheel`

The configuration step seems to be ok but my jetson nano freeze when 

> Building wheel torch-1.10.0a0+gitUnknown

This even if I have the 6GB swap file, are there any solutions for that ?

Here is a screen when I retried building :
![bdist_wheel](https://user-images.githubusercontent.com/79604981/164458113-0f2e38d8-0ef2-42b1-9d30-920b98a6fbb5.png)

I have cleared the build folder and am retrying with sudo. For now it seems not to freeze but hard to compile protobuf

**Comment by meeki007** [comment]
***Note about Security:***
I see people just willy nilly downloading wheels all over the place from all sorts of sources. You don't know me I don't have a community of checkers making sure I'm not bitcoin mining.

Before you download or do the below ask yourself if you really should trust the source. If you feel fine then great but do question before downloading any repository that is not official.

If this was for a production environment and not for personal use, I would build it myself .... again for security reasons. 


Wheels: for python 3.9.x - you may need to sort some package and dependency issues if you have not followed the build howto guide.

PyTorch: https://drive.google.com/file/d/1KgXe_1UOHMFkNHCQ9Wzp4jidDIKirkig/view?usp=sharing
TorchVision: https://drive.google.com/file/d/1tG2iTdmDvsQll_8bgr6wIrUz0ll8P0hT/view?usp=sharing

**Comment by loupdmer** [comment]
Thank you for your help and for your recommandation about security
For sure anybody must be aware when downloading any repository not official and for my part I allow myself being such compliant because it is for discovering on an embedded card for personal use :)

I will give you more information about my issue as soon as possible (tomorrow)

**Comment by meeki007** [comment]
updated document to reflect installing torchvision version needed based on Pytorch version installed. 

#### Torchvision requirements.txt
```
nano version.txt
```
change version to ***0.10.0*** if you installed pytorch 1.9.0 

change version to ***0.11.0*** if you installed pytorch 1.10.0 

CTRL+X to save changes and exit nano

**Comment by loupdmer** [comment]
Actually, I am not at this step yet, I am on building pytorch (before torchvision) at this step :

> **Start the build**
Altinstall of python - If you have another version of python installed and its not set to exec using python3 but rather its full ver name like python3.9 then change it to that name instead of python3.
`$ python3 setup.py bdist_wheel`

However, my jetson still freeze.
Here is the [build.log](https://github.com/meeki007/Jetpack-installs/files/8543458/build.log) file, I don't understand why.

**Comment by meeki007** [comment]
well it shows that your using the GNU 7.5.0 compiler and not the recommended Clang compiler
also i doubt this is and issue but your using Cmake 3.10.2 and I recommend 3.23.1

and you attach:
vec256_float_neon.h
AContext.cpp
KernelUtils.h

I don't think you edit them correctly.

**Comment by loupdmer** [comment]
According to cmake :

> `sudo apt install ninja-build git cmake -y`
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
ninja-build est déjà la version la plus récente (1.8.2-1).
cmake est déjà la version la plus récente (3.10.2-1ubuntu2.18.04.2).
git est déjà la version la plus récente (1:2.17.1-1ubuntu0.10).

It tells all packages are already the latest version, how is it possible for cmake if there is a 3.23.1 version ?

The file attached : [modified_files.zip](https://github.com/meeki007/Jetpack-installs/files/8544052/modified_files.zip)

It seems the used compiler is usr/bin/cc, and make program is /usr/bin/ninja.
I have checked and all the requirements are well installed, after many try it always stuck on the 34/5451th step

**Comment by meeki007** [comment]
What your describing is odd.
the CXX compiler should be using 
the clang compiler

Did you set it???
```
$ export CC=clang
$ export CXX=clang++
```

Is there a requirement you need for version 1.10.0 ???? you cant use 1.9.0 ???
I ask because I really don't want to tie up my jetson for 8hrs compiling 1.10.0 wheel for ya.
but if you have a need, besides just having the newest ver possible, I'll try to help ya out.

**Comment by loupdmer** [comment]
Hi,

I missed your cmake HowTo, I have installed cmake 3.23.1 and relaunched a build.
As you said it takes you 8 hours I will let it running many hours, hoping it passes at least the first 50th steps.

If it goes wrong, I will try 1.9.0 (I pick randomly the latest version)
Thank you for your time and your help

**Comment by loupdmer** [comment]
Hi, 
The build for version1.10 failed with cmake3.23.1, I am sure exporting clang as default compiler for C and CXX, but it still select gcc

However it works for 1.9.0, it takes around 20hours and some warnings but no errors.
It is weird because I think it used gcc for building too, but it works and all check are OK.

Same for torchvision, no issues.
